# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from fugle_fastapi_client.api.market_api import MarketApi
from fugle_fastapi_client.api.order_api import OrderApi
from fugle_fastapi_client.api.system_api import SystemApi
from fugle_fastapi_client.api.wallet_api import WalletApi

# import ApiClient
from fugle_fastapi_client.api_response import ApiResponse
from fugle_fastapi_client.api_client import ApiClient
from fugle_fastapi_client.configuration import Configuration
from fugle_fastapi_client.exceptions import OpenApiException
from fugle_fastapi_client.exceptions import ApiTypeError
from fugle_fastapi_client.exceptions import ApiValueError
from fugle_fastapi_client.exceptions import ApiKeyError
from fugle_fastapi_client.exceptions import ApiAttributeError
from fugle_fastapi_client.exceptions import ApiException

# import models into sdk package
from fugle_fastapi_client.models.ap_code import APCode
from fugle_fastapi_client.models.action import Action
from fugle_fastapi_client.models.bs_flag import BSFlag
from fugle_fastapi_client.models.balance_response import BalanceResponse
from fugle_fastapi_client.models.bid_ask import BidAsk
from fugle_fastapi_client.models.cancel_response import CancelResponse
from fugle_fastapi_client.models.create_order import CreateOrder
from fugle_fastapi_client.models.http_validation_error import HTTPValidationError
from fugle_fastapi_client.models.inventory_detail import InventoryDetail
from fugle_fastapi_client.models.inventory_response import InventoryResponse
from fugle_fastapi_client.models.k_line import KLine
from fugle_fastapi_client.models.k_lines_response import KLinesResponse
from fugle_fastapi_client.models.last_trade import LastTrade
from fugle_fastapi_client.models.last_trial import LastTrial
from fugle_fastapi_client.models.market_status_response import MarketStatusResponse
from fugle_fastapi_client.models.order_response import OrderResponse
from fugle_fastapi_client.models.order_result_response import OrderResultResponse
from fugle_fastapi_client.models.price_flag import PriceFlag
from fugle_fastapi_client.models.quote_response import QuoteResponse
from fugle_fastapi_client.models.settlement_response import SettlementResponse
from fugle_fastapi_client.models.total import Total
from fugle_fastapi_client.models.trade import Trade
from fugle_fastapi_client.models.validation_error import ValidationError
from fugle_fastapi_client.models.validation_error_loc_inner import ValidationErrorLocInner
