# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugle_fastapi_client.api.wallet_api import WalletApi


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WalletApi()

    def tearDown(self) -> None:
        pass

    def test_get_balance_endpoint_api_v1_balance_get(self) -> None:
        """Test case for get_balance_endpoint_api_v1_balance_get

        Get Balance Endpoint
        """
        pass

    def test_get_inventories_endpoint_api_v1_inventories_get(self) -> None:
        """Test case for get_inventories_endpoint_api_v1_inventories_get

        Get Inventories Endpoint
        """
        pass

    def test_get_settlements_endpoint_api_v1_settlements_get(self) -> None:
        """Test case for get_settlements_endpoint_api_v1_settlements_get

        Get Settlements Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
