# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.order_api import OrderApi


class TestOrderApi(unittest.TestCase):
    """OrderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderApi()

    def tearDown(self) -> None:
        pass

    def test_create_order_endpoint_api_v1_order_post(self) -> None:
        """Test case for create_order_endpoint_api_v1_order_post

        Create Order Endpoint
        """
        pass

    def test_delete_order_endpoint_api_v1_order_ord_no_delete(self) -> None:
        """Test case for delete_order_endpoint_api_v1_order_ord_no_delete

        Delete Order Endpoint
        """
        pass

    def test_get_market_status_endpoint_api_v1_market_status_get(self) -> None:
        """Test case for get_market_status_endpoint_api_v1_market_status_get

        Get Market Status Endpoint
        """
        pass

    def test_get_orders_endpoint_api_v1_orders_get(self) -> None:
        """Test case for get_orders_endpoint_api_v1_orders_get

        Get Orders Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
