# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_order import CreateOrder

class TestCreateOrder(unittest.TestCase):
    """CreateOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrder:
        """Test CreateOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrder`
        """
        model = CreateOrder()
        if include_optional:
            return CreateOrder(
                buy_sell = 'B',
                ap_code = '1',
                price_flag = '0',
                bs_flag = 'F',
                trade = '0',
                stock_no = '',
                quantity = 56,
                price = 1.337
            )
        else:
            return CreateOrder(
                buy_sell = 'B',
                ap_code = '1',
                price_flag = '0',
                bs_flag = 'F',
                trade = '0',
                stock_no = '',
                quantity = 56,
                price = 1.337,
        )
        """

    def testCreateOrder(self):
        """Test CreateOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
