# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.market_status_response import MarketStatusResponse

class TestMarketStatusResponse(unittest.TestCase):
    """MarketStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketStatusResponse:
        """Test MarketStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketStatusResponse`
        """
        model = MarketStatusResponse()
        if include_optional:
            return MarketStatusResponse(
                is_trading_day = True,
                last_trading_day = '',
                next_trading_day = ''
            )
        else:
            return MarketStatusResponse(
                is_trading_day = True,
                last_trading_day = '',
                next_trading_day = '',
        )
        """

    def testMarketStatusResponse(self):
        """Test MarketStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
