# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inventory_response import InventoryResponse

class TestInventoryResponse(unittest.TestCase):
    """InventoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryResponse:
        """Test InventoryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryResponse`
        """
        model = InventoryResponse()
        if include_optional:
            return InventoryResponse(
                ap_code = '',
                cost_qty = 1.337,
                cost_sum = 1.337,
                make_a_per = 1.337,
                make_a_sum = 1.337,
                price_avg = 1.337,
                price_evn = 1.337,
                price_mkt = 1.337,
                price_now = 1.337,
                price_qty_sum = 1.337,
                qty_b = 56,
                qty_bm = 56,
                qty_c = 56,
                qty_l = 56,
                qty_s = 56,
                qty_sm = 56,
                rec_va_sum = 1.337,
                s_type = '',
                stk_dats = [
                    openapi_client.models.inventory_detail.InventoryDetail(
                        buy_sell = '', 
                        cost_r = 1.337, 
                        fee = 1.337, 
                        make_a = 1.337, 
                        make_a_per = 1.337, 
                        ord_no = '', 
                        pay_n = 1.337, 
                        price = 1.337, 
                        price_evn = 1.337, 
                        qty = 56, 
                        qty_c = 56, 
                        qty_h = 56, 
                        qty_r = 56, 
                        t_date = '', 
                        t_time = '', 
                        tax = 1.337, 
                        tax_g = 1.337, 
                        trade = 56, 
                        value_mkt = 1.337, 
                        value_now = 1.337, 
                        user_def = '', )
                    ],
                stk_na = '',
                stk_no = '',
                trade = 56,
                value_mkt = 1.337,
                value_now = 1.337
            )
        else:
            return InventoryResponse(
                cost_qty = 1.337,
                cost_sum = 1.337,
                make_a_per = 1.337,
                make_a_sum = 1.337,
                price_avg = 1.337,
                price_evn = 1.337,
                price_mkt = 1.337,
                price_now = 1.337,
                price_qty_sum = 1.337,
                qty_b = 56,
                qty_bm = 56,
                qty_c = 56,
                qty_l = 56,
                qty_s = 56,
                qty_sm = 56,
                rec_va_sum = 1.337,
                s_type = '',
                stk_dats = [
                    openapi_client.models.inventory_detail.InventoryDetail(
                        buy_sell = '', 
                        cost_r = 1.337, 
                        fee = 1.337, 
                        make_a = 1.337, 
                        make_a_per = 1.337, 
                        ord_no = '', 
                        pay_n = 1.337, 
                        price = 1.337, 
                        price_evn = 1.337, 
                        qty = 56, 
                        qty_c = 56, 
                        qty_h = 56, 
                        qty_r = 56, 
                        t_date = '', 
                        t_time = '', 
                        tax = 1.337, 
                        tax_g = 1.337, 
                        trade = 56, 
                        value_mkt = 1.337, 
                        value_now = 1.337, 
                        user_def = '', )
                    ],
                stk_na = '',
                stk_no = '',
                value_mkt = 1.337,
                value_now = 1.337,
        )
        """

    def testInventoryResponse(self):
        """Test InventoryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
