# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugle_fastapi_client.models.ap_code import APCode

class TestAPCode(unittest.TestCase):
    """APCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPCode(self):
        """Test APCode"""
        # inst = APCode()

if __name__ == '__main__':
    unittest.main()
