# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugle_fastapi_client.api.market_api import MarketApi


class TestMarketApi(unittest.TestCase):
    """MarketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketApi()

    def tearDown(self) -> None:
        pass

    def test_get_candles_api_v1_historical_candles_get(self) -> None:
        """Test case for get_candles_api_v1_historical_candles_get

        Get Candles
        """
        pass

    def test_get_quote_api_v1_intraday_quote_get(self) -> None:
        """Test case for get_quote_api_v1_intraday_quote_get

        Get Quote
        """
        pass


if __name__ == '__main__':
    unittest.main()
