# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bs_flag import BSFlag

class TestBSFlag(unittest.TestCase):
    """BSFlag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBSFlag(self):
        """Test BSFlag"""
        # inst = BSFlag()

if __name__ == '__main__':
    unittest.main()
