# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugle_fastapi_client.models.balance_response import BalanceResponse

class TestBalanceResponse(unittest.TestCase):
    """BalanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceResponse:
        """Test BalanceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BalanceResponse`
        """
        model = BalanceResponse()
        if include_optional:
            return BalanceResponse(
                available_balance = 56,
                exchange_balance = 56,
                stock_pre_save_amount = 56
            )
        else:
            return BalanceResponse(
                available_balance = 56,
                exchange_balance = 56,
                stock_pre_save_amount = 56,
        )
        """

    def testBalanceResponse(self):
        """Test BalanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
