# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.total import Total

class TestTotal(unittest.TestCase):
    """Total unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Total:
        """Test Total
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Total`
        """
        model = Total()
        if include_optional:
            return Total(
                trade_value = 56,
                trade_volume = 56,
                trade_volume_at_bid = 56,
                trade_volume_at_ask = 56,
                transaction = 56,
                time = 56
            )
        else:
            return Total(
                trade_value = 56,
                trade_volume = 56,
                trade_volume_at_bid = 56,
                trade_volume_at_ask = 56,
                transaction = 56,
                time = 56,
        )
        """

    def testTotal(self):
        """Test Total"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
