# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inventory_detail import InventoryDetail

class TestInventoryDetail(unittest.TestCase):
    """InventoryDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryDetail:
        """Test InventoryDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryDetail`
        """
        model = InventoryDetail()
        if include_optional:
            return InventoryDetail(
                buy_sell = '',
                cost_r = 1.337,
                fee = 1.337,
                make_a = 1.337,
                make_a_per = 1.337,
                ord_no = '',
                pay_n = 1.337,
                price = 1.337,
                price_evn = 1.337,
                qty = 56,
                qty_c = 56,
                qty_h = 56,
                qty_r = 56,
                t_date = '',
                t_time = '',
                tax = 1.337,
                tax_g = 1.337,
                trade = 56,
                value_mkt = 1.337,
                value_now = 1.337,
                user_def = ''
            )
        else:
            return InventoryDetail(
                buy_sell = '',
                fee = 1.337,
                make_a = 1.337,
                make_a_per = 1.337,
                ord_no = '',
                pay_n = 1.337,
                price = 1.337,
                price_evn = 1.337,
                qty = 56,
                t_date = '',
                value_mkt = 1.337,
                value_now = 1.337,
        )
        """

    def testInventoryDetail(self):
        """Test InventoryDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
