# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.price_flag import PriceFlag

class TestPriceFlag(unittest.TestCase):
    """PriceFlag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceFlag(self):
        """Test PriceFlag"""
        # inst = PriceFlag()

if __name__ == '__main__':
    unittest.main()
