# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugle_fastapi_client.models.order_response import OrderResponse

class TestOrderResponse(unittest.TestCase):
    """OrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderResponse:
        """Test OrderResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderResponse`
        """
        model = OrderResponse()
        if include_optional:
            return OrderResponse(
                ord_date = '',
                ord_time = '',
                ord_type = '',
                ord_no = '',
                ret_code = '',
                ret_msg = '',
                work_date = ''
            )
        else:
            return OrderResponse(
                ord_date = '',
                ord_time = '',
                ord_type = '',
                ord_no = '',
                ret_code = '',
                ret_msg = '',
                work_date = '',
        )
        """

    def testOrderResponse(self):
        """Test OrderResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
